'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
type R=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);
const money=(v:any)=>Number(v||0).toLocaleString();
const pages=[['dash','📊','대시보드','工作台'],['customers','👥','고객관리','客户管理'],['cars','🔍','차량검색·입찰','找车竞拍'],['deals','💰','계약·수익','成交利润'],['quote','🧾','견적서','报价单']];
const statusList=['新客户','已联系','找车中','已推荐','待竞拍','已成交','暂停','无效'];
const sourceList=['抖音','小红书','直播','微信','Kakao','朋友介绍','其他'];
const resultList=['待确认','准备竞拍','未中标','已中标','放弃'];
const tr:Record<string,string>={
'新客户':'신규 고객','已联系':'연락 완료','找车中':'차량 검색 중','已推荐':'추천 완료','待竞拍':'입찰 대기','已成交':'계약 완료','暂停':'보류','无效':'무효',
'抖音':'더우인','小红书':'샤오홍슈','直播':'라이브 방송','微信':'위챗','朋友介绍':'지인 소개','其他':'기타',
'待确认':'확인 대기','准备竞拍':'입찰 준비','未中标':'유찰','已中标':'낙찰','放弃':'포기',
'是':'예','否':'아니오','A-高':'A-높음','B-中':'B-중간','C-低':'C-낮음'
};
const opt=(x:string)=><>{tr[x]||x}{tr[x]&&<span> / {x}</span>}</>;

function BTitle({ko,zh}:{ko:string,zh:string}){return <span className="btitle"><span className="btitle-ko">{ko}</span><span className="btitle-zh">{zh}</span></span>}
function Bi({ko,zh}:{ko:string,zh:string}){return <span className="bi"><span className="bi-ko">{ko}</span><span className="bi-zh">{zh}</span></span>}
function F({label,children}:{label:any,children:any}){return <div className="field"><label>{label}</label>{children}</div>}
function Logo({className='app-logo'}:{className?:string}){return <img className={className} src="/deking-logo.png" alt="CRM logo"/>}
function Table({h,rows}:{h:any[],rows:any[][]}){return <div className="tablewrap"><table className="table"><thead><tr>{h.map(x=><th key={typeof x==='string'?x:i}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function VehicleSelector({form,setForm,brands}:{form:R,setForm:(v:R)=>void,brands:string[]}){
 const [models,setModels]=useState<string[]>([]);
 const [loadingModels,setLoadingModels]=useState(false);

 useEffect(()=>{
  let active=true;
  setModels([]);
  if(!form.brand)return;
  setLoadingModels(true);
  supabase.rpc('get_car_models',{p_brand:form.brand}).then(({data,error})=>{
   if(!active)return;
   if(error){
    console.error('get_car_models:',error);
    setModels([]);
   }else{
    setModels((data||[]).map((x:any)=>x.model).filter(Boolean));
   }
   setLoadingModels(false);
  });
  return()=>{active=false};
 },[form.brand]);

 return <>
  <F label={<Bi ko="브랜드" zh="品牌"/>}>
   <select value={form.brand||''} onChange={e=>setForm({...form,brand:e.target.value,model:'',grade:''})}>
    <option value="">브랜드 선택 / 选择品牌</option>
    {brands.map(x=><option key={x} value={x}>{x}</option>)}
   </select>
  </F>
  <F label={<Bi ko="세부모델" zh="车型"/>}>
   <select value={form.model||''} disabled={!form.brand||loadingModels} onChange={e=>setForm({...form,model:e.target.value,grade:''})}>
    <option value="">{loadingModels?'모델 불러오는 중... / 车型加载中...':'모델 선택 / 选择车型'}</option>
    {models.map(x=><option key={x} value={x}>{x}</option>)}
   </select>
  </F>
  <F label={<Bi ko="트림·등급" zh="配置 / 等级"/>}>
   <input
    value={form.grade||''}
    onChange={e=>setForm({...form,grade:e.target.value})}
    placeholder="차량 광고 기준 입력 / 按车辆广告填写，例如：1.6 가솔린 프레스티지"
   />
  </F>
 </>;
}
export default function Home(){
 const [page,setPage]=useState('dash'),[loading,setLoading]=useState(true),[customers,setCustomers]=useState<R[]>([]),[cars,setCars]=useState<R[]>([]),[deals,setDeals]=useState<R[]>([]),[modal,setModal]=useState<any>(null),[search,setSearch]=useState('');
 const [brands,setBrands]=useState<string[]>([]);
 async function load(){setLoading(true);const[c,v,d,b]=await Promise.all([supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('vehicle_search').select('*').order('created_at',{ascending:false}),supabase.from('deals').select('*').order('deal_date',{ascending:false}),supabase.rpc('get_car_brands')]);setCustomers(c.data||[]);setCars(v.data||[]);setDeals(d.data||[]);setBrands((b.data||[]).map((x:any)=>x.brand));setLoading(false)}
 useEffect(()=>{load();const ch=supabase.channel('deking-v41').on('postgres_changes',{event:'*',schema:'public',table:'customers'},load).on('postgres_changes',{event:'*',schema:'public',table:'vehicle_search'},load).on('postgres_changes',{event:'*',schema:'public',table:'deals'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 const due=customers.filter(c=>c.next_contact&&c.next_contact<=today()&&!['已成交','无效'].includes(c.status));
 const month=today().slice(0,7),monthDeals=deals.filter(d=>(d.deal_date||'').slice(0,7)===month),monthProfit=monthDeals.reduce((s,d)=>s+Number(d.total_profit??(Number(d.broker_fee||0)+Number(d.car_profit||0)+Number(d.loan_fee||0)+Number(d.insurance_fee||0)+Number(d.extra_profit||0)-Number(d.expense||0))),0);
 const findName=(id:any)=>customers.find(c=>c.id===id)?.name||'';
 function CustomerForm({item}:{item?:R}){
  const [f,setF]=useState<R>(item||{customer_no:'',name:'',phone:'',wechat:'',source:'抖音',brand:'',model:'',grade:'',budget:'',year_request:'',mileage_request:'',color:'',loan:'待确认',probability:'B-中',status:'新客户',last_contact:today(),next_contact:today(),memo:''});
  async function save(){if(!f.name?.trim())return alert('고객명을 입력하세요 / 请输入客户姓名');const obj={...f,budget:f.budget?Number(f.budget):null,mileage_request:f.mileage_request?Number(f.mileage_request):null};const r=item?.id?await supabase.from('customers').update(obj).eq('id',item.id):await supabase.from('customers').insert(obj);if(r.error)return alert(r.error.message);setModal(null);load()}
  async function del(){if(item?.id&&confirm('이 고객을 삭제하시겠습니까? / 确认删除这个客户？')){const r=await supabase.from('customers').delete().eq('id',item.id);if(r.error)return alert(r.error.message);setModal(null);load()}}
  return <><div className="grid"><F label={<Bi ko="고객번호" zh="客户编号"/>}><input value={f.customer_no||''} onChange={e=>setF({...f,customer_no:e.target.value})}/></F><F label={<Bi ko="고객명" zh="姓名"/>}><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F><F label={<Bi ko="연락처" zh="电话"/>}><input value={f.phone||''} onChange={e=>setF({...f,phone:e.target.value})}/></F><F label={<Bi ko="WeChat · Kakao" zh="微信 / Kakao"/>}><input value={f.wechat||''} onChange={e=>setF({...f,wechat:e.target.value})}/></F><F label={<Bi ko="유입경로" zh="来源"/>}><select value={f.source||''} onChange={e=>setF({...f,source:e.target.value})}>{sourceList.map(x=><option key={x} value={x}>{tr[x]||x} / {x}</option>)}</select></F>
  <VehicleSelector form={f} setForm={setF} brands={brands}/>
  <F label={<Bi ko="예산 (만원)" zh="预算（万韩元）"/>}><input type="number" value={f.budget||''} onChange={e=>setF({...f,budget:e.target.value})}/></F><F label={<Bi ko="연식 조건" zh="年份要求"/>}><input value={f.year_request||''} onChange={e=>setF({...f,year_request:e.target.value})}/></F><F label={<Bi ko="주행거리 조건" zh="公里数要求"/>}><input type="number" value={f.mileage_request||''} onChange={e=>setF({...f,mileage_request:e.target.value})}/></F><F label={<Bi ko="색상" zh="颜色"/>}><input value={f.color||''} onChange={e=>setF({...f,color:e.target.value})}/></F><F label={<Bi ko="대출" zh="贷款"/>}><select value={f.loan||''} onChange={e=>setF({...f,loan:e.target.value})}>{['是','否','待确认'].map(x=><option key={x} value={x}>{tr[x]||x} / {x}</option>)}</select></F><F label={<Bi ko="구매 의향" zh="意向等级"/>}><select value={f.probability||''} onChange={e=>setF({...f,probability:e.target.value})}>{['A-高','B-中','C-低'].map(x=><option key={x} value={x}>{tr[x]||x} / {x}</option>)}</select></F><F label={<Bi ko="상태" zh="状态"/>}><select value={f.status||''} onChange={e=>setF({...f,status:e.target.value})}>{statusList.map(x=><option key={x} value={x}>{tr[x]||x} / {x}</option>)}</select></F><F label={<Bi ko="최근 연락일" zh="最后联系"/>}><input type="date" value={f.last_contact||''} onChange={e=>setF({...f,last_contact:e.target.value})}/></F><F label={<Bi ko="다음 연락일" zh="下次联系"/>}><input type="date" value={f.next_contact||''} onChange={e=>setF({...f,next_contact:e.target.value})}/></F><F label={<Bi ko="메모" zh="备注"/>}><textarea value={f.memo||''} onChange={e=>setF({...f,memo:e.target.value})}/></F></div><div className="toolbar" style={{marginTop:14}}><button className="btn" onClick={save}><Bi ko="저장" zh="保存"/></button>{item?.id&&<button className="btn red" onClick={del}><Bi ko="삭제" zh="删除"/></button>}</div></>
 }
 function CarForm({item}:{item?:R}){
  const [f,setF]=useState<R>(item||{customer_id:customers[0]?.id||'',record_date:today(),auction_place:'Glovis',brand:'',model:'',grade:'',year:'',mileage:'',color:'',vehicle_ref:'',market_price:'',expected_price:'',customer_max_price:'',auction_date:today(),result:'待确认',final_price:'',feedback:'',memo:''});
  async function save(){if(!f.customer_id)return alert('고객을 선택하세요 / 请选择客户');const nums=['year','mileage','market_price','expected_price','customer_max_price','final_price'];let o={...f};nums.forEach(k=>o[k]=o[k]?Number(o[k]):null);const r=item?.id?await supabase.from('vehicle_search').update(o).eq('id',item.id):await supabase.from('vehicle_search').insert(o);if(r.error)return alert(r.error.message);setModal(null);load()}
  async function del(){if(item?.id&&confirm('이 차량 검색 기록을 삭제하시겠습니까? / 确认删除这条找车记录？')){const r=await supabase.from('vehicle_search').delete().eq('id',item.id);if(r.error)return alert(r.error.message);setModal(null);load()}}
  return <><div className="grid"><F label={<Bi ko="고객" zh="客户"/>}><select value={f.customer_id||''} onChange={e=>setF({...f,customer_id:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name} / {c.phone}</option>)}</select></F><F label={<Bi ko="등록일" zh="日期"/>}><input type="date" value={f.record_date||''} onChange={e=>setF({...f,record_date:e.target.value})}/></F><F label={<Bi ko="경매장" zh="竞买场"/>}><input value={f.auction_place||''} onChange={e=>setF({...f,auction_place:e.target.value})}/></F>
  <VehicleSelector form={f} setForm={setF} brands={brands}/>
  <F label={<Bi ko="연식" zh="年份"/>}><input type="number" value={f.year||''} onChange={e=>setF({...f,year:e.target.value})}/></F><F label={<Bi ko="주행거리" zh="公里数"/>}><input type="number" value={f.mileage||''} onChange={e=>setF({...f,mileage:e.target.value})}/></F><F label={<Bi ko="색상" zh="颜色"/>}><input value={f.color||''} onChange={e=>setF({...f,color:e.target.value})}/></F><F label={<Bi ko="차량 링크·번호" zh="车辆链接/编号"/>}><input value={f.vehicle_ref||''} onChange={e=>setF({...f,vehicle_ref:e.target.value})}/></F><F label={<Bi ko="예상 시세 (만원)" zh="预计市场价（万）"/>}><input type="number" value={f.market_price||''} onChange={e=>setF({...f,market_price:e.target.value})}/></F><F label={<Bi ko="권장 최고 입찰가 (만원)" zh="建议最高价（万）"/>}><input type="number" value={f.expected_price||''} onChange={e=>setF({...f,expected_price:e.target.value})}/></F><F label={<Bi ko="고객 최고 입찰가 (만원)" zh="客户最高价（万）"/>}><input type="number" value={f.customer_max_price||''} onChange={e=>setF({...f,customer_max_price:e.target.value})}/></F><F label={<Bi ko="입찰일" zh="竞拍日期"/>}><input type="date" value={f.auction_date||''} onChange={e=>setF({...f,auction_date:e.target.value})}/></F><F label={<Bi ko="입찰 결과" zh="结果"/>}><select value={f.result||''} onChange={e=>setF({...f,result:e.target.value})}>{resultList.map(x=><option key={x} value={x}>{tr[x]||x} / {x}</option>)}</select></F><F label={<Bi ko="낙찰가 (만원)" zh="成交价（万）"/>}><input type="number" value={f.final_price||''} onChange={e=>setF({...f,final_price:e.target.value})}/></F><F label={<Bi ko="고객 피드백·다음 단계" zh="客户反馈/下一步"/>}><input value={f.feedback||''} onChange={e=>setF({...f,feedback:e.target.value})}/></F><F label={<Bi ko="메모" zh="备注"/>}><textarea value={f.memo||''} onChange={e=>setF({...f,memo:e.target.value})}/></F></div><div className="toolbar" style={{marginTop:14}}><button className="btn" onClick={save}><Bi ko="저장" zh="保存"/></button>{item?.id&&<button className="btn red" onClick={del}><Bi ko="삭제" zh="删除"/></button>}</div></>
 }
 function DealForm({item}:{item?:R}){
  const [f,setF]=useState<R>(item||{customer_id:customers[0]?.id||'',deal_date:today(),model:'',year:'',deal_price:'',broker_fee:'',car_profit:'',loan_fee:'',insurance_fee:'',extra_profit:'',expense:'',delivery_date:'',after_sales_reminder:'',memo:''});
  const total=Number(f.broker_fee||0)+Number(f.car_profit||0)+Number(f.loan_fee||0)+Number(f.insurance_fee||0)+Number(f.extra_profit||0)-Number(f.expense||0);
  async function save(){if(!f.customer_id)return alert('고객을 선택하세요 / 请选择客户');let o={...f,total_profit:total};['year','deal_price','broker_fee','car_profit','loan_fee','insurance_fee','extra_profit','expense'].forEach(k=>o[k]=o[k]?Number(o[k]):0);const r=item?.id?await supabase.from('deals').update(o).eq('id',item.id):await supabase.from('deals').insert(o);if(r.error)return alert(r.error.message);await supabase.from('customers').update({status:'已成交'}).eq('id',f.customer_id);setModal(null);load()}
  async function del(){if(item?.id&&confirm('이 계약 기록을 삭제하시겠습니까? / 确认删除成交记录？')){const r=await supabase.from('deals').delete().eq('id',item.id);if(r.error)return alert(r.error.message);setModal(null);load()}}
  return <><div className="grid"><F label={<Bi ko="고객" zh="客户"/>}><select value={f.customer_id||''} onChange={e=>setF({...f,customer_id:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></F><F label={<Bi ko="계약일" zh="成交日期"/>}><input type="date" value={f.deal_date||''} onChange={e=>setF({...f,deal_date:e.target.value})}/></F><F label={<Bi ko="차종" zh="车型"/>}><input value={f.model||''} onChange={e=>setF({...f,model:e.target.value})}/></F><F label={<Bi ko="연식" zh="年份"/>}><input type="number" value={f.year||''} onChange={e=>setF({...f,year:e.target.value})}/></F><F label={<Bi ko="낙찰가 (만원)" zh="成交价（万）"/>}><input type="number" value={f.deal_price||''} onChange={e=>setF({...f,deal_price:e.target.value})}/></F><F label={<Bi ko="경매대행 수수료" zh="代拍服务费"/>}><input type="number" value={f.broker_fee||''} onChange={e=>setF({...f,broker_fee:e.target.value})}/></F><F label={<Bi ko="차량 수익" zh="车辆利润"/>}><input type="number" value={f.car_profit||''} onChange={e=>setF({...f,car_profit:e.target.value})}/></F><F label={<Bi ko="대출 수익" zh="贷款返点"/>}><input type="number" value={f.loan_fee||''} onChange={e=>setF({...f,loan_fee:e.target.value})}/></F><F label={<Bi ko="보험 수익" zh="保险返点"/>}><input type="number" value={f.insurance_fee||''} onChange={e=>setF({...f,insurance_fee:e.target.value})}/></F><F label={<Bi ko="기타 수입" zh="其他收入"/>}><input type="number" value={f.extra_profit||''} onChange={e=>setF({...f,extra_profit:e.target.value})}/></F><F label={<Bi ko="지출·할인" zh="支出/优惠"/>}><input type="number" value={f.expense||''} onChange={e=>setF({...f,expense:e.target.value})}/></F><F label={<Bi ko="총수익" zh="总利润"/>}><input value={total} readOnly/></F><F label={<Bi ko="출고일" zh="交车日期"/>}><input type="date" value={f.delivery_date||''} onChange={e=>setF({...f,delivery_date:e.target.value})}/></F><F label={<Bi ko="사후관리 알림" zh="售后提醒"/>}><input value={f.after_sales_reminder||''} onChange={e=>setF({...f,after_sales_reminder:e.target.value})}/></F><F label={<Bi ko="메모" zh="备注"/>}><textarea value={f.memo||''} onChange={e=>setF({...f,memo:e.target.value})}/></F></div><div className="toolbar" style={{marginTop:14}}><button className="btn" onClick={save}><Bi ko="저장" zh="保存"/></button>{item?.id&&<button className="btn red" onClick={del}><Bi ko="삭제" zh="删除"/></button>}</div></>
 }
 function Quote(){
  const [f,setF]=useState<R>({customer_id:'',name:'',phone:'',model:'',year:'',mileage:'',color:'',expected:'',fee:'',auction_place:'Glovis',valid_until:'',memo:''});
  function pick(id:string){const c=customers.find(x=>x.id===id);setF({...f,customer_id:id,name:c?.name||'',phone:c?.phone||'',model:[c?.brand,c?.model,c?.grade].filter(Boolean).join(' ')})}
  const total=Number(f.expected||0)+Number(f.fee||0);
  const fields=[['고객명','客户姓名',f.name],['연락처','电话',f.phone],['차종','车型',f.model],['연식','年份',f.year],['주행거리','公里数',f.mileage],['색상','颜色',f.color],['예상 낙찰가(만원)','预计成交价(万韩元)',money(f.expected)],['경매대행 수수료(만원)','代拍服务费(万韩元)',money(f.fee)],['예상 총액(만원)','预计总价(万韩元)',money(total)],['경매장','竞买场',f.auction_place],['유효기간','有效期',f.valid_until],['메모','备注',f.memo]];
  return <><div className="card no-print"><h2><BTitle ko="견적 입력" zh="报价内容"/></h2><div className="grid"><F label={<Bi ko="고객 선택" zh="选择客户"/>}><select value={f.customer_id} onChange={e=>pick(e.target.value)}><option value="">고객 선택 / 请选择</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} / {c.phone}</option>)}</select></F>{[['name','고객명','客户姓名'],['phone','연락처','电话'],['model','차종','车型'],['year','연식','年份'],['mileage','주행거리','公里数'],['color','색상','颜色'],['expected','예상 낙찰가 (만원)','预计成交价（万）'],['fee','경매대행 수수료 (만원)','代拍服务费（万）'],['auction_place','경매장','竞买场'],['valid_until','유효기간','有效期'],['memo','메모','备注']].map(([k,ko,zh])=><F key={k} label={<Bi ko={ko} zh={zh}/>}><input type={['expected','fee'].includes(k)?'number':k==='valid_until'?'date':'text'} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></F>)}</div><div className="toolbar" style={{marginTop:14}}><button className="btn" onClick={()=>window.print()}><Bi ko="인쇄 · PDF 저장" zh="打印 / 保存 PDF"/></button></div></div><div className="card quote"><h2><span className="quote-title"><Logo className="quote-logo"/><BTitle ko="중고차 경매대행 견적서" zh="韩国二手车代拍报价单"/></span></h2><table><tbody><tr><td>한국어</td><td>中文</td><td>입력 내용 / 填写内容</td></tr>{fields.map(x=><tr key={x[0]}><td>{x[0]}</td><td>{x[1]}</td><td>{x[2]}</td></tr>)}</tbody></table><p className="muted">본 견적은 경매대행 참고 견적이며 최종 금액은 실제 낙찰가, 차량 확인 및 실비 기준으로 확정됩니다.<br/><span className="quote-zh">本报价为代拍参考价，最终金额以实际成交价、车辆检查及实际费用为准。</span></p></div></>
 }
 function content(){
  if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return <div className="notice">Vercel에서 NEXT_PUBLIC_SUPABASE_URL 및 NEXT_PUBLIC_SUPABASE_ANON_KEY를 먼저 설정하세요. / 请先在 Vercel 设置环境变量。</div>;
  if(loading)return <div className="card"><Bi ko="데이터 불러오는 중..." zh="正在读取数据..."/></div>;
  if(page==='dash')return <><div className="kpis"><div className="kpi"><span><Bi ko="오늘 연락" zh="今日待联系"/></span><b>{due.length}</b></div><div className="kpi"><span><Bi ko="차량 검색 중" zh="找车中"/></span><b>{customers.filter(c=>c.status==='找车中').length}</b></div><div className="kpi"><span><Bi ko="오늘 입찰" zh="今日竞拍"/></span><b>{cars.filter(v=>v.auction_date===today()).length}</b></div><div className="kpi"><span><Bi ko="이번 달 계약" zh="本月成交"/></span><b>{monthDeals.length}</b></div><div className="kpi"><span><Bi ko="이번 달 수익 (만원)" zh="本月利润（万）"/></span><b>{money(monthProfit)}</b></div></div><div className="card"><h2><BTitle ko="오늘 우선 연락 고객" zh="今日优先联系客户"/></h2><Table h={[<Bi ko='고객명' zh='姓名'/>,<Bi ko='연락처' zh='电话'/>,<Bi ko='희망 차종' zh='需求车型'/>,<Bi ko='예산' zh='预算'/>,<Bi ko='상태' zh='状态'/>,<Bi ko='다음 연락' zh='下次联系'/>,<Bi ko='메모' zh='备注'/>,<Bi ko='관리' zh='管理'/>]} rows={due.map(c=>[c.name,c.phone,[c.brand,c.model].filter(Boolean).join(' '),money(c.budget),c.status,<span className="due">{c.next_contact}</span>,c.memo,<button className="btn gray" onClick={()=>setModal({title:<Bi ko="고객 수정" zh="修改客户"/>,body:<CustomerForm item={c}/>})}><Bi ko="수정" zh="修改"/></button>])}/></div><div className="card"><h2><BTitle ko="사용 방법" zh="使用方法"/></h2><p>매일 여기만 확인하세요. 연락 예정 고객 → 입찰 → 계약 후 수익 기록 순서로 처리합니다. 금액 단위는 만원입니다。 / 每天只看这里：先联系到期客户，再处理竞拍，成交后记利润。金额统一为万韩元。</p></div></>;
  if(page==='customers'){const q=search.toLowerCase(),list=customers.filter(c=>!q||JSON.stringify(c).toLowerCase().includes(q));return <div className="card"><h2><BTitle ko="고객관리" zh="客户管理"/></h2><div className="toolbar"><input className="search" placeholder="고객명·연락처·차종 검색 / 姓名、电话、车型搜索" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn" onClick={()=>setModal({title:<Bi ko="신규 고객" zh="新客户"/>,body:<CustomerForm/>})}><Bi ko="+ 신규 고객" zh="新增客户"/></button></div><Table h={[<Bi ko='번호' zh='编号'/>,<Bi ko='고객명' zh='姓名'/>,<Bi ko='연락처' zh='电话'/>,<Bi ko='유입경로' zh='来源'/>,<Bi ko='희망 차종' zh='需求车型'/>,<Bi ko='예산' zh='预算'/>,<Bi ko='구매 의향' zh='意向'/>,<Bi ko='상태' zh='状态'/>,<Bi ko='다음 연락' zh='下次联系'/>,<Bi ko='관리' zh='管理'/>]} rows={list.map(c=>[c.customer_no,c.name,c.phone,c.source,[c.brand,c.model,c.grade].filter(Boolean).join(' '),money(c.budget),c.probability,c.status,c.next_contact,<button className="btn gray" onClick={()=>setModal({title:<Bi ko="고객 수정" zh="修改客户"/>,body:<CustomerForm item={c}/>})}><Bi ko="수정" zh="修改"/></button>])}/></div>}
  if(page==='cars')return <div className="card"><h2><BTitle ko="차량검색·입찰" zh="找车竞拍"/></h2><div className="toolbar"><button className="btn" onClick={()=>setModal({title:<Bi ko="차량 검색·입찰 추가" zh="新增找车竞拍"/>,body:<CarForm/>})}><Bi ko="+ 차량 검색·입찰 추가" zh="新增找车竞拍"/></button></div><Table h={[<Bi ko='고객' zh='客户'/>,<Bi ko='등록일' zh='日期'/>,<Bi ko='경매장' zh='竞买场'/>,<Bi ko='차종·트림' zh='车型/配置'/>,<Bi ko='연식' zh='年份'/>,<Bi ko='주행거리' zh='公里数'/>,<Bi ko='시세' zh='市场价'/>,<Bi ko='권장 최고가' zh='建议最高价'/>,<Bi ko='고객 최고가' zh='客户最高价'/>,<Bi ko='입찰일' zh='竞拍日'/>,<Bi ko='결과' zh='结果'/>,<Bi ko='낙찰가' zh='成交价'/>,<Bi ko='다음 단계' zh='下一步'/>,<Bi ko='관리' zh='管理'/>]} rows={cars.map(v=>[findName(v.customer_id),v.record_date,v.auction_place,[v.brand,v.model,v.grade].filter(Boolean).join(' '),v.year,money(v.mileage),money(v.market_price),money(v.expected_price),money(v.customer_max_price),v.auction_date,v.result,money(v.final_price),v.feedback,<button className="btn gray" onClick={()=>setModal({title:<Bi ko="차량 검색·입찰 수정" zh="修改找车竞拍"/>,body:<CarForm item={v}/>})}><Bi ko="수정" zh="修改"/></button>])}/></div>;
  if(page==='deals')return <div className="card"><h2><BTitle ko="계약·수익" zh="成交利润"/></h2><div className="toolbar"><button className="btn" onClick={()=>setModal({title:<Bi ko="계약·수익 추가" zh="新增成交利润"/>,body:<DealForm/>})}><Bi ko="+ 계약·수익 추가" zh="新增成交"/></button></div><Table h={[<Bi ko='계약일' zh='成交日'/>,<Bi ko='고객' zh='客户'/>,<Bi ko='차종' zh='车型'/>,<Bi ko='낙찰가' zh='成交价'/>,<Bi ko='대행 수수료' zh='服务费'/>,<Bi ko='차량 수익' zh='车辆利润'/>,<Bi ko='대출' zh='贷款'/>,<Bi ko='보험' zh='保险'/>,<Bi ko='기타' zh='其他'/>,<Bi ko='지출' zh='支出'/>,<Bi ko='총수익' zh='总利润'/>,<Bi ko='출고일' zh='交车日'/>,<Bi ko='관리' zh='管理'/>]} rows={deals.map(d=>[d.deal_date,findName(d.customer_id),d.model,money(d.deal_price),money(d.broker_fee),money(d.car_profit),money(d.loan_fee),money(d.insurance_fee),money(d.extra_profit),money(d.expense),<b>{money(d.total_profit)}</b>,d.delivery_date,<button className="btn gray" onClick={()=>setModal({title:<Bi ko="계약·수익 수정" zh="修改成交利润"/>,body:<DealForm item={d}/>})}><Bi ko="수정" zh="修改"/></button>])}/></div>;
  return <Quote/>
 }
 return <><header className="top"><div><div className="top-title"><Logo className="top-logo"/><h1>중고차 경매대행 CRM Professional V4.1</h1></div><p><span className="top-ko">한국 중고차 개인 업무 시스템</span><span className="top-zh">韩国二手车个人工作系统 · 手机 / 电脑同步</span></p></div><button className="btn gray" onClick={load}><span className="btn-ko">새로고침</span><span className="btn-zh">刷新</span></button></header><div className="shell"><nav className="nav"><div className="brand"><Logo className="nav-logo"/><span className="muted">Professional V4.1</span></div>{pages.map(p=><button key={p[0]} className={page===p[0]?'active':''} onClick={()=>{setPage(p[0]);setSearch('')}}><span className="menu-icon">{p[1]}</span><span className="menu-text"><span className="menu-ko">{p[2]}</span><span className="menu-zh">{p[3]}</span></span></button>)}</nav><main className="main">{content()}</main></div><nav className="mobilebar">{pages.map(p=><button key={p[0]} className={page===p[0]?'active':''} onClick={()=>{setPage(p[0]);setSearch('')}}><span className="mobile-icon">{p[1]}</span><span className="mobile-ko">{p[2]}</span><span className="mobile-zh">{p[3]}</span></button>)}</nav>{modal&&<div className="modalbg" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalhead"><h2>{modal.title}</h2><button className="btn gray" onClick={()=>setModal(null)}>✕</button></div>{modal.body}</div></div>}</>
}